language: python	
python:	
 - "3.6"
cache: pip	
install:	
 - pip install -r requirements.txt
 - pip install coveralls
 - pip install codeclimate-test-reporter
services:
 - postgresql
before_script:
- createdb test_store_db
- createdb store_manager
 
script:	
 - nosetests tests/test_authentication.py --with-coverage 
after_success:
 - coveralls
 - codeclimate-test-reporter
