language: python	
python:	
 - "3.6"
cache: pip	
install:	
 - pip install -r requirements.txt
 - pip install coveralls
 - pip install codeclimate-test-reporter
services:
 - postgresql
before_script:
 - "psql -c CREATE DATABASE test_store_db;"
 - "psql -c CREATE DATABASE store_manager;"
 - "psql -c CREATE USER postgres WITH PASSWORD 'chacha';"
 - "psql -c GRANT ALL PRIVILEGES ON DATABASE test_store_db TO postgres;"
 - "psql -c GRANT ALL PRIVILEGES ON DATABASE store_manager TO postgres;"
 
script:	
 - nosetests tests --with-coverage 
after_success:
 - coveralls
 - codeclimate-test-reporter
