language: python	
python:	
 - "3.6"
cache: pip	
install:	
 - pip install -r requirements.txt
 - pip install coveralls
 - pip install codeclimate-test-reporter
services:
 - postgresql
before_script:
 - psql -c 'create database test_store_db;' -U postgres
 - psql -c "ALTER USER postgres WITH PASSWORD 'chacha';" -U postgres

env:
 
 - DATABASE_URL="dbname='test_store_db' user='postgres' host='localhost' password='chacha'"
script:	
 - nosetests tests --with-coverage
after_success:
 - coveralls
 - codeclimate-test-reporter
