language: python	
python:	
 - "3.6"
cache: pip	
install:	
 - pip install -r requirements.txt
 - pip install coveralls
 - pip install codeclimate-test-reporter
services:
 - postgresql
before_script:
- psql -c 'create database test_store_db;' -U postgres
- psql -c 'create database store_manager;' -U postgres
- python migrage.py
 
script:	
 - nosetests tests/test_authentication.py --with-coverage 
after_success:
 - coveralls
 - codeclimate-test-reporter
